# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chetu-ingress
  namespace: chetu-ns
spec:
  rules:
    - host: chetu.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chetu-deployment
                port:
                  number: 80
