name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Lint Tool
        run: pip install flake8

      - name: Run Lint Check
        run: flake8 app.py

  sast:
    name: Static Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r app.py --skip B104

  test:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit Tests
        run: pytest -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build App
        run: echo "Building application"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Using Secrets
        run: echo "Using API_KEY securely"
        env:
          API_KEY: ${{ secrets.API_KEY }}

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Package artifact
        run: |
          mkdir build
          cp app.py requirements.txt build/
          tar -czf flask-app.tar.gz build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact-flask
          path: flask-app.tar.gz

  deploy-dev:
    runs-on: ubuntu-latest
    needs: package
    environment: dev
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact-flask

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV"
          tar -xzf flask-app.tar.gz

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact-flask

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD"
          tar -xzf flask-app.tar.gz
